# Generated by Django 5.0.2 on 2024-02-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('preparation_time', models.PositiveIntegerField(help_text='Preparation in minutes')),
                ('cooking_time', models.PositiveIntegerField(help_text='Cooking time in minutes')),
                ('total_time', models.PositiveIntegerField(help_text='Total time in minutes')),
                ('servings', models.PositiveIntegerField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='recipe-images/')),
                ('categories', models.CharField(max_length=50)),
            ],
        ),
    ]
