# Generated by Django 5.0.2 on 2024-02-20 11:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('preparation_time', models.PositiveIntegerField(help_text='Preparation in minutes')),
                ('cooking_time', models.PositiveIntegerField(help_text='Cooking time in minutes')),
                ('total_time', models.PositiveIntegerField(help_text='Total time in minutes')),
                ('servings', models.PositiveIntegerField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='recipe-images/')),
                ('categories', models.ManyToManyField(related_name='recipes', to='Recipe.category')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('score', models.IntegerField(help_text='Enter a value between 1 - 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rating', to='Recipe.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='Recipe.recipe')),
            ],
        ),
    ]
