# Generated by Django 5.0.2 on 2024-02-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="recipe-images"),
        ),
    ]
