# Generated by Django 5.0.2 on 2024-02-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
