# Generated by Django 5.0.2 on 2024-02-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Recipe", "0004_alter_recipe_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_vegetarian",
            field=models.BooleanField(
                default=False, help_text="Check if the recipe is vegetarian"
            ),
        ),
    ]
