# Generated by Django 5.0.2 on 2024-02-23 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Recipe", "0005_recipe_is_vegetarian"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="procedure",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
