# Generated by Django 5.0.2 on 2024-02-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Recipe", "0006_recipe_procedure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Recipe.recipe"
            ),
        ),
    ]
